version: "3.9"
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: 123
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: 4316b7d169a708cbb349b370f66e9b5b22c3e0ecebbdca59a31bece28f155d9b
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: fastapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: